# Generated by Django 3.1 on 2020-08-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Username'),
        ),
    ]
